services:
  - type: web
    name: redditdmbots
    rootDir: web_dashboard  # Points to the correct directory
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install --upgrade pip
      pip install gunicorn==21.2.0 flask-socketio==5.3.6
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
    preDeployCommand: |
      echo "Running pre-deploy tasks..."
    postDeployCommand: |
      echo "Post-deploy tasks complete"

