services:
  - type: web
    name: reddit-bot-dashboard
    env: python
    buildCommand: |
      pip install -r web_dashboard/requirements.txt
    startCommand: gunicorn -w 4 web_dashboard.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CONFIG_PATH
        value: web_dashboard/config/config.json